package by.jwd.lemesheuski.hostel.controller.command_helper;

public enum CommandName {
    LOCAL_CHANGE, MAIN, LOG_OUT, PROFILE, SIGN_UP, LOG_IN, SET_ROOM_PARAMS, NO_SUCH_COMMAND, APARTMENTS,
    ADD_APARTMENT, SELECT_APARTMENTS, RESERVATION, SHOPPING_CART, SELECT_APARTMENTS_WITH_DATE,
    EDIT_TYPE, EDIT_NUMBER_OF_BED, EDIT_NUMBER_OF_ROOM, CONFIRM_PAYMENT, ORDERS, EDIT_APARTMENT
}
