package by.jwd.lemesheuski.hostel.controller.command_helper;

public enum CommandName {
    LOCAL_CHANGE, MAIN, LOG_OUT, PROFILE, SIGN_UP, LOG_IN, PASSWORD_CHANGE, SET_ROOM_PARAMS, NO_SUCH_COMMAND, APARTMENTS, ADD_APARTMENT,
    SELECT_APARTMENTS, RESERVATION, SHOPPING_CART, SELECT_APARTMENTS_WITH_DATE, ADD_TYPE, ADD_NOB, ADD_NOR,
    CONFIRM_PAYMENT, ORDERS, EDIT_APARTMENT, DEACTIVATE_APARTMENT, ORDER_DETAILS, ALL_ROOM_SERVICES, ADD_ROOM_SERVICE,
    EDIT_ROOM_SERVICE, ADD_ROOM_SERVICE_TO_ORDER, DEACTIVATE_ROOM_SERVICE, CONFIRM_SERVICE_PAYMENT
}
